gravity_controller:
    type: gravity_compensation_controller/GravityCompensationController
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    kp_gains:
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.1
    kd_gains:
        - 0.01
        - 0.01
        - 0.01
        - 0.01
        - 0.01
        - 0.01
        - 0.01
    torque_limits:
        - 2.0
        - 2.0
        - 2.0
        - 2.0
        - 2.0
        - 2.0
        - 2.0
    alpha: 0.0
